MODE: 1             # 1: train, 2: test, 3: eval
MODEL: 2            # 1:boundary model, 2:inpainting model_w_only_l1_loss, 3:inpainting model, 4:all_joint
MASK: 1             # 1:random extrapolation mask  2:static extrapolation mask
SEED: 10            # random seed
GPU: [0]            # list of gpu ids
DEBUG: 0            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console
LOADED_IMAGE_SIZE: 256
HEIGHT_R1: 2        # the magnification of height in outpainting result 
WIDTH_R2: 2         # the magnification of width in outpainting result
# HEIGHT_OUTPUT_SIZE: 256     # height output size
# WIDTH_AUGMENT_SIZE: 256     # width output size

BOUNDING_MODEL_GENERATOR: 0 #
INPAINTING_MODEL_FEATURE_GENERATOR: 0 #checkpoints/cityscapes/saved_model/InpaintingModel/InpaintingModel_gen_iter_50000_only_l1.pth
INPAINTING_MODEL_INPAINTING_GENERATOR: 0
INPAINTING_MODEL_INPAINTING_DISCRIMINATOR: 0 #checkpoints/cityscapes/saved_model/InpaintingModel/InpaintingModel_dis_iter_150000_step6_mae_0734.pth


TRAIN_FLIST: ../datasets/celeba/celeba_train.flist
VAL_FLIST: ../datasets/celeba/celeba_valid.flist
TEST_FLIST: ../datasets/celeba/celeba_test.flist

LR: 0.0001                    # learning rate #model IV use 2e-5
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
BATCH_SIZE: 4                 # input batch size for training
INPUT_SIZE: 256               # input image size for training 0 for original size
SIGMA: 2                      # standard deviation of the Gaussian filter used in Canny edge detector (0: random, -1: no edge)
MAX_ITERS: 50001             # maximum number of iterations to train the model

GAN_LOSS_ALPHA: 0.001
WGAN_GP_LAMBDA: 10
PRETRAIN_L1_ALPHA: 1.2
L1_LOSS_ALPHA: 4.2
AE_LOSS_ALPHA: 1.2
MRF_ALPHA: 0.05
FA_ALPHA: 0.5



GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size

SAVE_INTERVAL: 5          # how many iterations to wait before saving model (0: never)
SAMPLE_INTERVAL: 5        # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 12               # number of images to sample
EVAL_INTERVAL: 0              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 100             # how many iterations to wait before logging training status (0: never)
TEST_SAMPLE_NUMBER: 20        # how many testing sample should be tested (-1: no limit)
